### PR TITLE
feat(browser): change browser color every second for 10 seconds

### PR DESCRIPTION
**Pull request by christinepham**
Used `setInterval` to time a new random color being generated every second, then used a count variable to make it happen 10 times

### CODE REVIEW

**Review by hamstra — CHANGES_REQUESTED** [review]
Right now your solution cycles through 9 different colors instead of 10, can you tell me why and fix it so that it cycles through 10?

Also, not in the original specs, but can you change this code so that there isn't any use of global variables?

**Comment by veem-abba** [comment]
It looks like your code does not check if a color has been used before. Can you include that functionality?

**Comment by christinepham** [comment]
`var colors = [];
var repeat = setInterval(function() {
	var hue;
	hue = 'rgb(' + (Math.floor(Math.random() * 256)) + ',' + (Math.floor(Math.random() * 256)) + ',' + (Math.floor(Math.random() * 256)) + ')';
	if (colors.length < 10) {
		if (!colors.includes(hue)) {
			colors.push(hue);
			document.body.style.backgroundColor = hue;
		}
	} else { 
		clearInterval(repeat);
	} 
}, 1000);`

**Comment by veem-abba** [comment]
It looks like the code can possibly run for longer than 10 seconds if the color generator generates an already-used color.

Additionally, if the color generator returns an already-used color, then the previously set color will remain on-screen for longer than 1 second.

**Pull request merged**
